updated docker file

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -88,7 +88,8 @@ jobs:
 
       - name: Stop and remove  container if running
         run: |
-            docker ps -q --filter "name=mltest" | grep -q . && docker stop mltest && docker rm -fv mltest
+            docker ps -q --filter "name=mltest" | grep -q . && docker stop mltest && docker rm -fv mltest || echo "Container 'mltest' not found or already stopped."
+
        
       - name: Run Docker Image to serve users
         run: |
